services:
  base-job:
    build: .
    volumes:
      - ./job/:/usr/src/app/job
      - ./output:/usr/src/app/output
      - ./input:/usr/src/app/input

  notebook:
   build: notebook
   ports:
     - 8080:8080
   volumes:
     - ./notebook:/usr/src/app/notebook
   develop:
     watch:
       - path: ./notebook/requirements.txt
         action: rebuild

  tile:
    build: .
    volumes_from:
      - base-job
    command: [".venv/bin/python", "-m", "job.tile"]

  model_unet:
    build: .
    volumes_from:
      - base-job
    command: [".venv/bin/python", "-m", "job.model_unet"]

  apply_model:
    build: .
    volumes_from:
      - base-job
    command: [".venv/bin/python", "-m", "job.apply_model"]

  klhk_classification_s4g:
    build: .
    volumes_from:
      - base-job
    command: [".venv/bin/python", "-m", "job.klhk_classification_s4g"]
